// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package steward

import (
	"github.com/hyperledger/aries-framework-go/pkg/framework/aries/api"
	"github.com/scoir/canis/pkg/framework"
	"github.com/scoir/canis/pkg/schema"
)

// Injectors from wire.go:

func InitializeAgent(ctx api.Provider, conf *framework.Config) (*Steward, error) {
	client := schema.New(conf)
	steward, err := New(ctx, conf, client)
	if err != nil {
		return nil, err
	}
	return steward, nil
}
