dbpath: /data/agent
database: mongo
mongo:
   url: "mongodb://127.0.0.1:27017"
   database: "crux"

wsinbound:
  host: 0.0.0.0
  port: 8887
grpc:
  host: 0.0.0.0
  port: 8888
grpcBridge:
  host: 0.0.0.0
  port: 8889


runtime: kubernetes
namespace: canis
#imageRegistry: {{ .Values.imageRegistry }}
#dockerTag: {{ .Values.dockerTag }}
