dbpath: /data/steward
database: mongo
mongo:
   url: "mongodb://127.0.0.1:27017"
   database: "crux"

wsinbound:
  host: 0.0.0.0
  port: 9999
grpc:
  host: 0.0.0.0
  port: 7777
grpcBridge:
  host: 0.0.0.0
  port: 7778


runtime: kubernetes
namespace: canis
#imageRegistry: {{ .Values.imageRegistry }}
#dockerTag: {{ .Values.dockerTag }}
