// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steward/api/steward_agent.proto

package steward

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attribute_Type int32

const (
	Attribute_STRING Attribute_Type = 0
	Attribute_NUMBER Attribute_Type = 1
	Attribute_OBJECT Attribute_Type = 2
	Attribute_ARRAY  Attribute_Type = 3
	Attribute_BOOL   Attribute_Type = 4
	Attribute_NULL   Attribute_Type = 5
)

var Attribute_Type_name = map[int32]string{
	0: "STRING",
	1: "NUMBER",
	2: "OBJECT",
	3: "ARRAY",
	4: "BOOL",
	5: "NULL",
}

var Attribute_Type_value = map[string]int32{
	"STRING": 0,
	"NUMBER": 1,
	"OBJECT": 2,
	"ARRAY":  3,
	"BOOL":   4,
	"NULL":   5,
}

func (x Attribute_Type) String() string {
	return proto.EnumName(Attribute_Type_name, int32(x))
}

func (Attribute_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{3, 0}
}

type PublicDIDRequest struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Did                  string   `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Verkey               string   `protobuf:"bytes,3,opt,name=verkey,proto3" json:"verkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicDIDRequest) Reset()         { *m = PublicDIDRequest{} }
func (m *PublicDIDRequest) String() string { return proto.CompactTextString(m) }
func (*PublicDIDRequest) ProtoMessage()    {}
func (*PublicDIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{0}
}

func (m *PublicDIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicDIDRequest.Unmarshal(m, b)
}
func (m *PublicDIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicDIDRequest.Marshal(b, m, deterministic)
}
func (m *PublicDIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicDIDRequest.Merge(m, src)
}
func (m *PublicDIDRequest) XXX_Size() int {
	return xxx_messageInfo_PublicDIDRequest.Size(m)
}
func (m *PublicDIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicDIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicDIDRequest proto.InternalMessageInfo

func (m *PublicDIDRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *PublicDIDRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *PublicDIDRequest) GetVerkey() string {
	if m != nil {
		return m.Verkey
	}
	return ""
}

type PublicDIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicDIDResponse) Reset()         { *m = PublicDIDResponse{} }
func (m *PublicDIDResponse) String() string { return proto.CompactTextString(m) }
func (*PublicDIDResponse) ProtoMessage()    {}
func (*PublicDIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{1}
}

func (m *PublicDIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicDIDResponse.Unmarshal(m, b)
}
func (m *PublicDIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicDIDResponse.Marshal(b, m, deterministic)
}
func (m *PublicDIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicDIDResponse.Merge(m, src)
}
func (m *PublicDIDResponse) XXX_Size() int {
	return xxx_messageInfo_PublicDIDResponse.Size(m)
}
func (m *PublicDIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicDIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicDIDResponse proto.InternalMessageInfo

type Schema struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string       `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{2}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Schema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Schema) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Schema) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Attribute struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Attribute_Type `protobuf:"varint,2,opt,name=type,proto3,enum=steward.Attribute_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{3}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetType() Attribute_Type {
	if m != nil {
		return m.Type
	}
	return Attribute_STRING
}

type CreateSchemaRequest struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaRequest) Reset()         { *m = CreateSchemaRequest{} }
func (m *CreateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaRequest) ProtoMessage()    {}
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{4}
}

func (m *CreateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaRequest.Unmarshal(m, b)
}
func (m *CreateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaRequest.Marshal(b, m, deterministic)
}
func (m *CreateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaRequest.Merge(m, src)
}
func (m *CreateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaRequest.Size(m)
}
func (m *CreateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaRequest proto.InternalMessageInfo

func (m *CreateSchemaRequest) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type CreateSchemaResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchemaResponse) Reset()         { *m = CreateSchemaResponse{} }
func (m *CreateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSchemaResponse) ProtoMessage()    {}
func (*CreateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{5}
}

func (m *CreateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchemaResponse.Unmarshal(m, b)
}
func (m *CreateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchemaResponse.Marshal(b, m, deterministic)
}
func (m *CreateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchemaResponse.Merge(m, src)
}
func (m *CreateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSchemaResponse.Size(m)
}
func (m *CreateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchemaResponse proto.InternalMessageInfo

func (m *CreateSchemaResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListSchemaRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSchemaRequest) Reset()         { *m = ListSchemaRequest{} }
func (m *ListSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*ListSchemaRequest) ProtoMessage()    {}
func (*ListSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{6}
}

func (m *ListSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSchemaRequest.Unmarshal(m, b)
}
func (m *ListSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSchemaRequest.Marshal(b, m, deterministic)
}
func (m *ListSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSchemaRequest.Merge(m, src)
}
func (m *ListSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_ListSchemaRequest.Size(m)
}
func (m *ListSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSchemaRequest proto.InternalMessageInfo

func (m *ListSchemaRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListSchemaRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListSchemaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListSchemaRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ListSchemaResponse struct {
	Count                int64     `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Schema               []*Schema `protobuf:"bytes,2,rep,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListSchemaResponse) Reset()         { *m = ListSchemaResponse{} }
func (m *ListSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*ListSchemaResponse) ProtoMessage()    {}
func (*ListSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{7}
}

func (m *ListSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSchemaResponse.Unmarshal(m, b)
}
func (m *ListSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSchemaResponse.Marshal(b, m, deterministic)
}
func (m *ListSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSchemaResponse.Merge(m, src)
}
func (m *ListSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_ListSchemaResponse.Size(m)
}
func (m *ListSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSchemaResponse proto.InternalMessageInfo

func (m *ListSchemaResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListSchemaResponse) GetSchema() []*Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type GetSchemaRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchemaRequest) Reset()         { *m = GetSchemaRequest{} }
func (m *GetSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*GetSchemaRequest) ProtoMessage()    {}
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{8}
}

func (m *GetSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchemaRequest.Unmarshal(m, b)
}
func (m *GetSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchemaRequest.Marshal(b, m, deterministic)
}
func (m *GetSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchemaRequest.Merge(m, src)
}
func (m *GetSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_GetSchemaRequest.Size(m)
}
func (m *GetSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchemaRequest proto.InternalMessageInfo

func (m *GetSchemaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetSchemaResponse struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchemaResponse) Reset()         { *m = GetSchemaResponse{} }
func (m *GetSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*GetSchemaResponse) ProtoMessage()    {}
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{9}
}

func (m *GetSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchemaResponse.Unmarshal(m, b)
}
func (m *GetSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchemaResponse.Marshal(b, m, deterministic)
}
func (m *GetSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchemaResponse.Merge(m, src)
}
func (m *GetSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_GetSchemaResponse.Size(m)
}
func (m *GetSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchemaResponse proto.InternalMessageInfo

func (m *GetSchemaResponse) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type DeleteSchemaRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaRequest) Reset()         { *m = DeleteSchemaRequest{} }
func (m *DeleteSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaRequest) ProtoMessage()    {}
func (*DeleteSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{10}
}

func (m *DeleteSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaRequest.Unmarshal(m, b)
}
func (m *DeleteSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaRequest.Merge(m, src)
}
func (m *DeleteSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaRequest.Size(m)
}
func (m *DeleteSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaRequest proto.InternalMessageInfo

func (m *DeleteSchemaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSchemaResponse) Reset()         { *m = DeleteSchemaResponse{} }
func (m *DeleteSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSchemaResponse) ProtoMessage()    {}
func (*DeleteSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{11}
}

func (m *DeleteSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSchemaResponse.Unmarshal(m, b)
}
func (m *DeleteSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSchemaResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSchemaResponse.Merge(m, src)
}
func (m *DeleteSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSchemaResponse.Size(m)
}
func (m *DeleteSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSchemaResponse proto.InternalMessageInfo

type UpdateSchemaRequest struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaRequest) Reset()         { *m = UpdateSchemaRequest{} }
func (m *UpdateSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaRequest) ProtoMessage()    {}
func (*UpdateSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{12}
}

func (m *UpdateSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaRequest.Unmarshal(m, b)
}
func (m *UpdateSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaRequest.Merge(m, src)
}
func (m *UpdateSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaRequest.Size(m)
}
func (m *UpdateSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaRequest proto.InternalMessageInfo

func (m *UpdateSchemaRequest) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type UpdateSchemaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSchemaResponse) Reset()         { *m = UpdateSchemaResponse{} }
func (m *UpdateSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSchemaResponse) ProtoMessage()    {}
func (*UpdateSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{13}
}

func (m *UpdateSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSchemaResponse.Unmarshal(m, b)
}
func (m *UpdateSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSchemaResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSchemaResponse.Merge(m, src)
}
func (m *UpdateSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSchemaResponse.Size(m)
}
func (m *UpdateSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSchemaResponse proto.InternalMessageInfo

type Agent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AssignedSchemaId     string   `protobuf:"bytes,3,opt,name=assigned_schema_id,json=assignedSchemaId,proto3" json:"assigned_schema_id,omitempty"`
	EndorsableSchemaIds  []string `protobuf:"bytes,4,rep,name=endorsable_schema_ids,json=endorsableSchemaIds,proto3" json:"endorsable_schema_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{14}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetAssignedSchemaId() string {
	if m != nil {
		return m.AssignedSchemaId
	}
	return ""
}

func (m *Agent) GetEndorsableSchemaIds() []string {
	if m != nil {
		return m.EndorsableSchemaIds
	}
	return nil
}

type CreateAgentRequest struct {
	Agent                *Agent   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentRequest) Reset()         { *m = CreateAgentRequest{} }
func (m *CreateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgentRequest) ProtoMessage()    {}
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{15}
}

func (m *CreateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentRequest.Unmarshal(m, b)
}
func (m *CreateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentRequest.Marshal(b, m, deterministic)
}
func (m *CreateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentRequest.Merge(m, src)
}
func (m *CreateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgentRequest.Size(m)
}
func (m *CreateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentRequest proto.InternalMessageInfo

func (m *CreateAgentRequest) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

type CreateAgentResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentResponse) Reset()         { *m = CreateAgentResponse{} }
func (m *CreateAgentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAgentResponse) ProtoMessage()    {}
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{16}
}

func (m *CreateAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentResponse.Unmarshal(m, b)
}
func (m *CreateAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentResponse.Marshal(b, m, deterministic)
}
func (m *CreateAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentResponse.Merge(m, src)
}
func (m *CreateAgentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAgentResponse.Size(m)
}
func (m *CreateAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentResponse proto.InternalMessageInfo

func (m *CreateAgentResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListAgentRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAgentRequest) Reset()         { *m = ListAgentRequest{} }
func (m *ListAgentRequest) String() string { return proto.CompactTextString(m) }
func (*ListAgentRequest) ProtoMessage()    {}
func (*ListAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{17}
}

func (m *ListAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentRequest.Unmarshal(m, b)
}
func (m *ListAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentRequest.Marshal(b, m, deterministic)
}
func (m *ListAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentRequest.Merge(m, src)
}
func (m *ListAgentRequest) XXX_Size() int {
	return xxx_messageInfo_ListAgentRequest.Size(m)
}
func (m *ListAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentRequest proto.InternalMessageInfo

func (m *ListAgentRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListAgentRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAgentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListAgentResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Agents               []*Agent `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAgentResponse) Reset()         { *m = ListAgentResponse{} }
func (m *ListAgentResponse) String() string { return proto.CompactTextString(m) }
func (*ListAgentResponse) ProtoMessage()    {}
func (*ListAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{18}
}

func (m *ListAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentResponse.Unmarshal(m, b)
}
func (m *ListAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentResponse.Marshal(b, m, deterministic)
}
func (m *ListAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentResponse.Merge(m, src)
}
func (m *ListAgentResponse) XXX_Size() int {
	return xxx_messageInfo_ListAgentResponse.Size(m)
}
func (m *ListAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentResponse proto.InternalMessageInfo

func (m *ListAgentResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListAgentResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type GetAgentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentRequest) Reset()         { *m = GetAgentRequest{} }
func (m *GetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentRequest) ProtoMessage()    {}
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{19}
}

func (m *GetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentRequest.Unmarshal(m, b)
}
func (m *GetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentRequest.Marshal(b, m, deterministic)
}
func (m *GetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentRequest.Merge(m, src)
}
func (m *GetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentRequest.Size(m)
}
func (m *GetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentRequest proto.InternalMessageInfo

func (m *GetAgentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAgentResponse struct {
	Agent                *Agent   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentResponse) Reset()         { *m = GetAgentResponse{} }
func (m *GetAgentResponse) String() string { return proto.CompactTextString(m) }
func (*GetAgentResponse) ProtoMessage()    {}
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{20}
}

func (m *GetAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentResponse.Unmarshal(m, b)
}
func (m *GetAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentResponse.Marshal(b, m, deterministic)
}
func (m *GetAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentResponse.Merge(m, src)
}
func (m *GetAgentResponse) XXX_Size() int {
	return xxx_messageInfo_GetAgentResponse.Size(m)
}
func (m *GetAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentResponse proto.InternalMessageInfo

func (m *GetAgentResponse) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

type DeleteAgentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentRequest) Reset()         { *m = DeleteAgentRequest{} }
func (m *DeleteAgentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentRequest) ProtoMessage()    {}
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{21}
}

func (m *DeleteAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentRequest.Unmarshal(m, b)
}
func (m *DeleteAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentRequest.Merge(m, src)
}
func (m *DeleteAgentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentRequest.Size(m)
}
func (m *DeleteAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentRequest proto.InternalMessageInfo

func (m *DeleteAgentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentResponse) Reset()         { *m = DeleteAgentResponse{} }
func (m *DeleteAgentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentResponse) ProtoMessage()    {}
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{22}
}

func (m *DeleteAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentResponse.Unmarshal(m, b)
}
func (m *DeleteAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentResponse.Merge(m, src)
}
func (m *DeleteAgentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentResponse.Size(m)
}
func (m *DeleteAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentResponse proto.InternalMessageInfo

type UpdateAgentRequest struct {
	Agent                *Agent   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAgentRequest) Reset()         { *m = UpdateAgentRequest{} }
func (m *UpdateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAgentRequest) ProtoMessage()    {}
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{23}
}

func (m *UpdateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAgentRequest.Unmarshal(m, b)
}
func (m *UpdateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAgentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAgentRequest.Merge(m, src)
}
func (m *UpdateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAgentRequest.Size(m)
}
func (m *UpdateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAgentRequest proto.InternalMessageInfo

func (m *UpdateAgentRequest) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

type UpdateAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAgentResponse) Reset()         { *m = UpdateAgentResponse{} }
func (m *UpdateAgentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAgentResponse) ProtoMessage()    {}
func (*UpdateAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{24}
}

func (m *UpdateAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAgentResponse.Unmarshal(m, b)
}
func (m *UpdateAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAgentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAgentResponse.Merge(m, src)
}
func (m *UpdateAgentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAgentResponse.Size(m)
}
func (m *UpdateAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAgentResponse proto.InternalMessageInfo

type LaunchAgentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LaunchAgentRequest) Reset()         { *m = LaunchAgentRequest{} }
func (m *LaunchAgentRequest) String() string { return proto.CompactTextString(m) }
func (*LaunchAgentRequest) ProtoMessage()    {}
func (*LaunchAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{25}
}

func (m *LaunchAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchAgentRequest.Unmarshal(m, b)
}
func (m *LaunchAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchAgentRequest.Marshal(b, m, deterministic)
}
func (m *LaunchAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchAgentRequest.Merge(m, src)
}
func (m *LaunchAgentRequest) XXX_Size() int {
	return xxx_messageInfo_LaunchAgentRequest.Size(m)
}
func (m *LaunchAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchAgentRequest proto.InternalMessageInfo

func (m *LaunchAgentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type LaunchAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LaunchAgentResponse) Reset()         { *m = LaunchAgentResponse{} }
func (m *LaunchAgentResponse) String() string { return proto.CompactTextString(m) }
func (*LaunchAgentResponse) ProtoMessage()    {}
func (*LaunchAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{26}
}

func (m *LaunchAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchAgentResponse.Unmarshal(m, b)
}
func (m *LaunchAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchAgentResponse.Marshal(b, m, deterministic)
}
func (m *LaunchAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchAgentResponse.Merge(m, src)
}
func (m *LaunchAgentResponse) XXX_Size() int {
	return xxx_messageInfo_LaunchAgentResponse.Size(m)
}
func (m *LaunchAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchAgentResponse proto.InternalMessageInfo

type ShutdownAgentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownAgentRequest) Reset()         { *m = ShutdownAgentRequest{} }
func (m *ShutdownAgentRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownAgentRequest) ProtoMessage()    {}
func (*ShutdownAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{27}
}

func (m *ShutdownAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownAgentRequest.Unmarshal(m, b)
}
func (m *ShutdownAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownAgentRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownAgentRequest.Merge(m, src)
}
func (m *ShutdownAgentRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownAgentRequest.Size(m)
}
func (m *ShutdownAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownAgentRequest proto.InternalMessageInfo

func (m *ShutdownAgentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ShutdownAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownAgentResponse) Reset()         { *m = ShutdownAgentResponse{} }
func (m *ShutdownAgentResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownAgentResponse) ProtoMessage()    {}
func (*ShutdownAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{28}
}

func (m *ShutdownAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownAgentResponse.Unmarshal(m, b)
}
func (m *ShutdownAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownAgentResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownAgentResponse.Merge(m, src)
}
func (m *ShutdownAgentResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownAgentResponse.Size(m)
}
func (m *ShutdownAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownAgentResponse proto.InternalMessageInfo

type AgentInvitiationRequest struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInvitiationRequest) Reset()         { *m = AgentInvitiationRequest{} }
func (m *AgentInvitiationRequest) String() string { return proto.CompactTextString(m) }
func (*AgentInvitiationRequest) ProtoMessage()    {}
func (*AgentInvitiationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{29}
}

func (m *AgentInvitiationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInvitiationRequest.Unmarshal(m, b)
}
func (m *AgentInvitiationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInvitiationRequest.Marshal(b, m, deterministic)
}
func (m *AgentInvitiationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInvitiationRequest.Merge(m, src)
}
func (m *AgentInvitiationRequest) XXX_Size() int {
	return xxx_messageInfo_AgentInvitiationRequest.Size(m)
}
func (m *AgentInvitiationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInvitiationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInvitiationRequest proto.InternalMessageInfo

func (m *AgentInvitiationRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

type AgentInivitationResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInivitationResponse) Reset()         { *m = AgentInivitationResponse{} }
func (m *AgentInivitationResponse) String() string { return proto.CompactTextString(m) }
func (*AgentInivitationResponse) ProtoMessage()    {}
func (*AgentInivitationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f85888aae65dae54, []int{30}
}

func (m *AgentInivitationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInivitationResponse.Unmarshal(m, b)
}
func (m *AgentInivitationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInivitationResponse.Marshal(b, m, deterministic)
}
func (m *AgentInivitationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInivitationResponse.Merge(m, src)
}
func (m *AgentInivitationResponse) XXX_Size() int {
	return xxx_messageInfo_AgentInivitationResponse.Size(m)
}
func (m *AgentInivitationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInivitationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInivitationResponse proto.InternalMessageInfo

func (m *AgentInivitationResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("steward.Attribute_Type", Attribute_Type_name, Attribute_Type_value)
	proto.RegisterType((*PublicDIDRequest)(nil), "steward.PublicDIDRequest")
	proto.RegisterType((*PublicDIDResponse)(nil), "steward.PublicDIDResponse")
	proto.RegisterType((*Schema)(nil), "steward.Schema")
	proto.RegisterType((*Attribute)(nil), "steward.Attribute")
	proto.RegisterType((*CreateSchemaRequest)(nil), "steward.CreateSchemaRequest")
	proto.RegisterType((*CreateSchemaResponse)(nil), "steward.CreateSchemaResponse")
	proto.RegisterType((*ListSchemaRequest)(nil), "steward.ListSchemaRequest")
	proto.RegisterType((*ListSchemaResponse)(nil), "steward.ListSchemaResponse")
	proto.RegisterType((*GetSchemaRequest)(nil), "steward.GetSchemaRequest")
	proto.RegisterType((*GetSchemaResponse)(nil), "steward.GetSchemaResponse")
	proto.RegisterType((*DeleteSchemaRequest)(nil), "steward.DeleteSchemaRequest")
	proto.RegisterType((*DeleteSchemaResponse)(nil), "steward.DeleteSchemaResponse")
	proto.RegisterType((*UpdateSchemaRequest)(nil), "steward.UpdateSchemaRequest")
	proto.RegisterType((*UpdateSchemaResponse)(nil), "steward.UpdateSchemaResponse")
	proto.RegisterType((*Agent)(nil), "steward.Agent")
	proto.RegisterType((*CreateAgentRequest)(nil), "steward.CreateAgentRequest")
	proto.RegisterType((*CreateAgentResponse)(nil), "steward.CreateAgentResponse")
	proto.RegisterType((*ListAgentRequest)(nil), "steward.ListAgentRequest")
	proto.RegisterType((*ListAgentResponse)(nil), "steward.ListAgentResponse")
	proto.RegisterType((*GetAgentRequest)(nil), "steward.GetAgentRequest")
	proto.RegisterType((*GetAgentResponse)(nil), "steward.GetAgentResponse")
	proto.RegisterType((*DeleteAgentRequest)(nil), "steward.DeleteAgentRequest")
	proto.RegisterType((*DeleteAgentResponse)(nil), "steward.DeleteAgentResponse")
	proto.RegisterType((*UpdateAgentRequest)(nil), "steward.UpdateAgentRequest")
	proto.RegisterType((*UpdateAgentResponse)(nil), "steward.UpdateAgentResponse")
	proto.RegisterType((*LaunchAgentRequest)(nil), "steward.LaunchAgentRequest")
	proto.RegisterType((*LaunchAgentResponse)(nil), "steward.LaunchAgentResponse")
	proto.RegisterType((*ShutdownAgentRequest)(nil), "steward.ShutdownAgentRequest")
	proto.RegisterType((*ShutdownAgentResponse)(nil), "steward.ShutdownAgentResponse")
	proto.RegisterType((*AgentInvitiationRequest)(nil), "steward.AgentInvitiationRequest")
	proto.RegisterType((*AgentInivitationResponse)(nil), "steward.AgentInivitationResponse")
}

func init() { proto.RegisterFile("steward/api/steward_agent.proto", fileDescriptor_f85888aae65dae54) }

var fileDescriptor_f85888aae65dae54 = []byte{
	// 1075 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x26, 0xbf, 0x6d, 0x4e, 0x4a, 0xeb, 0x4e, 0x92, 0x36, 0x75, 0x52, 0xb6, 0x3b, 0x74, 0xcb,
	0x0a, 0x50, 0x22, 0x05, 0x2e, 0x10, 0x42, 0x2b, 0xa5, 0xdb, 0xa5, 0x0a, 0x0a, 0x2d, 0x38, 0x2d,
	0x50, 0x09, 0x11, 0x39, 0xf5, 0x28, 0x1d, 0x91, 0xda, 0xc1, 0x9e, 0x74, 0xd5, 0x22, 0x6e, 0xe0,
	0x9a, 0x2b, 0x2e, 0x78, 0x30, 0x5e, 0x81, 0xe7, 0x40, 0xc8, 0x33, 0x63, 0x67, 0xc6, 0x76, 0x77,
	0xab, 0xd5, 0x5e, 0x75, 0x66, 0xce, 0x99, 0xef, 0x3b, 0x7f, 0xf3, 0xc5, 0x85, 0x47, 0x01, 0x23,
	0x2f, 0x6d, 0xdf, 0xe9, 0xda, 0x73, 0xda, 0x95, 0xeb, 0xb1, 0x3d, 0x25, 0x2e, 0xeb, 0xcc, 0x7d,
	0x8f, 0x79, 0x68, 0x45, 0x1e, 0x9a, 0xed, 0xa9, 0xe7, 0x4d, 0x67, 0x84, 0x3b, 0xda, 0xae, 0xeb,
	0x31, 0x9b, 0x51, 0xcf, 0x0d, 0x84, 0x1b, 0xfe, 0x1e, 0x8c, 0x6f, 0x16, 0x93, 0x19, 0xbd, 0x3c,
	0x1a, 0x1c, 0x59, 0xe4, 0x97, 0x05, 0x09, 0x18, 0xda, 0x81, 0x55, 0x8e, 0x34, 0xa6, 0x4e, 0x33,
	0xb7, 0x97, 0x7b, 0x5a, 0xb1, 0x56, 0xf8, 0x7e, 0xe0, 0x20, 0x03, 0x0a, 0x0e, 0x75, 0x9a, 0x79,
	0x7e, 0x1a, 0x2e, 0xd1, 0x16, 0x94, 0x6f, 0x88, 0xff, 0x33, 0xb9, 0x6d, 0x16, 0xf8, 0xa1, 0xdc,
	0xe1, 0x1a, 0x6c, 0x2a, 0xc0, 0xc1, 0xdc, 0x73, 0x03, 0x82, 0xef, 0xa0, 0x3c, 0xba, 0xbc, 0x22,
	0xd7, 0x36, 0x5a, 0x87, 0x7c, 0x8c, 0x9e, 0xa7, 0x0e, 0x42, 0x50, 0x74, 0xed, 0x6b, 0x22, 0x91,
	0xf9, 0x1a, 0x35, 0x61, 0xe5, 0x86, 0xf8, 0x01, 0xf5, 0x5c, 0x89, 0x1d, 0x6d, 0x51, 0x0f, 0xc0,
	0x66, 0xcc, 0xa7, 0x93, 0x05, 0x23, 0x41, 0xb3, 0xb8, 0x57, 0x78, 0x5a, 0xed, 0xa1, 0x8e, 0xcc,
	0xb8, 0xd3, 0x8f, 0x4c, 0x96, 0xe2, 0x85, 0xff, 0xce, 0x41, 0x25, 0xb6, 0xc4, 0x7c, 0x39, 0x85,
	0xef, 0x23, 0x28, 0xb2, 0xdb, 0xb9, 0x88, 0x61, 0xbd, 0xb7, 0x9d, 0xc6, 0xeb, 0x9c, 0xdd, 0xce,
	0x89, 0xc5, 0x9d, 0xf0, 0x00, 0x8a, 0xe1, 0x0e, 0x01, 0x94, 0x47, 0x67, 0xd6, 0xe0, 0xe4, 0xd8,
	0x78, 0x27, 0x5c, 0x9f, 0x9c, 0x7f, 0x7d, 0xf8, 0xc2, 0x32, 0x72, 0xe1, 0xfa, 0xf4, 0xf0, 0xab,
	0x17, 0xcf, 0xcf, 0x8c, 0x3c, 0xaa, 0x40, 0xa9, 0x6f, 0x59, 0xfd, 0x0b, 0xa3, 0x80, 0x56, 0xa1,
	0x78, 0x78, 0x7a, 0x3a, 0x34, 0x8a, 0xe1, 0xea, 0xe4, 0x7c, 0x38, 0x34, 0x4a, 0xf8, 0x19, 0xd4,
	0x9e, 0xfb, 0xc4, 0x66, 0x44, 0xd4, 0x26, 0x6a, 0xc3, 0x07, 0x50, 0x0e, 0xf8, 0x01, 0x0f, 0xb2,
	0xda, 0xdb, 0x88, 0x03, 0x92, 0x7e, 0xd2, 0x8c, 0x0f, 0xa0, 0xae, 0xdf, 0x17, 0xd5, 0x4e, 0xd6,
	0x18, 0x33, 0xd8, 0x1c, 0xd2, 0x80, 0xe9, 0x2c, 0x75, 0x28, 0x05, 0xcc, 0xf6, 0x19, 0xf7, 0x2b,
	0x58, 0x62, 0x83, 0x5a, 0x50, 0x99, 0xdb, 0x53, 0x32, 0x0e, 0xe8, 0x9d, 0xa8, 0x47, 0xc1, 0x5a,
	0x0d, 0x0f, 0x46, 0xf4, 0x6e, 0x59, 0xbb, 0x42, 0x76, 0xaf, 0x8a, 0x5a, 0xaf, 0xf0, 0x08, 0x90,
	0xca, 0x2a, 0x63, 0xab, 0x43, 0xe9, 0xd2, 0x5b, 0xb8, 0x31, 0x2d, 0xdf, 0x28, 0x29, 0xe7, 0x79,
	0x4f, 0xef, 0x4d, 0x19, 0x83, 0x71, 0x4c, 0x12, 0x99, 0x24, 0xd3, 0xfd, 0x02, 0x36, 0x15, 0x1f,
	0xc9, 0xfb, 0xe0, 0xa2, 0x3e, 0x81, 0xda, 0x11, 0x99, 0x91, 0x64, 0x53, 0x92, 0x24, 0x5b, 0x50,
	0xd7, 0xdd, 0xe4, 0xa4, 0x3f, 0x83, 0xda, 0xf9, 0xdc, 0x79, 0xf3, 0x9e, 0x6e, 0x41, 0x5d, 0xbf,
	0x2f, 0x71, 0xff, 0xcc, 0x41, 0xa9, 0x1f, 0x3e, 0xc6, 0x07, 0xbd, 0xa0, 0x8f, 0x01, 0xd9, 0x41,
	0x40, 0xa7, 0x2e, 0x71, 0xc6, 0x02, 0x38, 0x7c, 0xd3, 0xa2, 0x6f, 0x46, 0x64, 0x11, 0x0c, 0x03,
	0x07, 0xf5, 0xa0, 0x41, 0x5c, 0xc7, 0xf3, 0x03, 0x7b, 0x32, 0x23, 0x4b, 0x7f, 0xf1, 0xc0, 0x2a,
	0x56, 0x6d, 0x69, 0x8c, 0xae, 0x04, 0xf8, 0x73, 0x40, 0x62, 0xf6, 0x78, 0x50, 0x51, 0x9a, 0xfb,
	0x50, 0xe2, 0x8a, 0x21, 0xb3, 0x5c, 0x5f, 0x3e, 0x25, 0xee, 0x25, 0x8c, 0x61, 0x89, 0xb5, 0xbb,
	0xf7, 0x8c, 0xed, 0x05, 0x18, 0xe1, 0x00, 0x69, 0x04, 0x6f, 0x67, 0x6a, 0xf1, 0xb7, 0xe2, 0x45,
	0xe8, 0xfc, 0xd9, 0xa3, 0x79, 0x00, 0x65, 0x1e, 0x75, 0x20, 0x47, 0x33, 0x99, 0x93, 0xb4, 0xe2,
	0xc7, 0xb0, 0x71, 0x4c, 0xf4, 0x60, 0x93, 0x09, 0x7d, 0xc6, 0x87, 0x57, 0x27, 0x7d, 0x58, 0xc5,
	0xf6, 0x01, 0x89, 0x69, 0x7b, 0x25, 0x7e, 0x23, 0x1a, 0x5d, 0x8d, 0x22, 0x6c, 0x95, 0x18, 0xa9,
	0x37, 0x68, 0x55, 0x23, 0x1a, 0x67, 0x1d, 0x72, 0x1f, 0xd0, 0xd0, 0x5e, 0xb8, 0x97, 0x57, 0xaf,
	0x8b, 0x47, 0xf3, 0x92, 0x97, 0x0f, 0xa0, 0x3e, 0xba, 0x5a, 0x30, 0xc7, 0x7b, 0xe9, 0xbe, 0xf2,
	0xfa, 0x36, 0x34, 0x12, 0x7e, 0x12, 0xe0, 0x53, 0xd8, 0xe6, 0x07, 0x03, 0xf7, 0x86, 0x32, 0xca,
	0x7f, 0xd6, 0x5e, 0xff, 0x13, 0x86, 0x3b, 0xd0, 0x94, 0xb7, 0xe8, 0x0d, 0x65, 0xf2, 0x96, 0xec,
	0x02, 0x82, 0xe2, 0xc4, 0x73, 0x6e, 0xa3, 0x5f, 0x85, 0x70, 0xdd, 0xfb, 0x0f, 0xa0, 0xd4, 0x77,
	0xae, 0xa9, 0x8b, 0x7e, 0x84, 0x35, 0x55, 0x67, 0x51, 0x3b, 0xae, 0x55, 0x86, 0x7c, 0x9b, 0xbb,
	0xf7, 0x58, 0x65, 0xf0, 0x1b, 0xbf, 0xff, 0xf3, 0xef, 0x5f, 0xf9, 0x0a, 0x5e, 0xe9, 0x8a, 0x87,
	0x86, 0xbe, 0x03, 0x58, 0xea, 0x24, 0x32, 0xe3, 0xdb, 0x29, 0xc9, 0x36, 0x5b, 0x99, 0x36, 0x1d,
	0x17, 0xc5, 0xb8, 0x3f, 0x40, 0x25, 0x96, 0x41, 0xb4, 0x13, 0x5f, 0x4d, 0xca, 0xa7, 0x69, 0x66,
	0x99, 0x24, 0x68, 0x9d, 0x83, 0xae, 0xa3, 0x35, 0x09, 0xda, 0xfd, 0x95, 0x3a, 0xbf, 0x21, 0x1b,
	0xd6, 0x54, 0xed, 0x53, 0xea, 0x91, 0xa1, 0x9c, 0x4a, 0x3d, 0x32, 0x05, 0x53, 0x52, 0x7c, 0xa8,
	0x53, 0x5c, 0xc1, 0x9a, 0x2a, 0x83, 0x0a, 0x45, 0x86, 0xba, 0x2a, 0x14, 0x99, 0xda, 0xd9, 0xe2,
	0x14, 0x0d, 0x5c, 0x8b, 0x29, 0xc4, 0xdf, 0x4e, 0xc8, 0x74, 0x01, 0x55, 0x45, 0x8c, 0x50, 0x2b,
	0xd1, 0x3d, 0x75, 0x42, 0xcd, 0x76, 0xb6, 0x31, 0xd5, 0x59, 0x21, 0x09, 0x68, 0x04, 0x95, 0x58,
	0x65, 0x94, 0x0e, 0x24, 0x45, 0xcd, 0x34, 0xb3, 0x4c, 0xa9, 0xb6, 0x4a, 0xd0, 0x73, 0x58, 0x8d,
	0x44, 0x04, 0x35, 0xd5, 0xd6, 0x69, 0x90, 0x3b, 0x19, 0x96, 0x54, 0x4f, 0x05, 0xa2, 0x28, 0xf8,
	0x4f, 0x50, 0x55, 0xb4, 0x43, 0x29, 0x43, 0x5a, 0x77, 0xcc, 0x76, 0xb6, 0x31, 0xd5, 0x50, 0x15,
	0xdf, 0x81, 0xaa, 0x22, 0x24, 0x0a, 0x7e, 0x5a, 0x9a, 0xcc, 0x76, 0xb6, 0x51, 0xe2, 0x9b, 0x1c,
	0xbf, 0x8e, 0x51, 0x8c, 0x2f, 0x3e, 0x7f, 0x43, 0x16, 0x02, 0x55, 0x45, 0x71, 0x14, 0x96, 0xb4,
	0x5a, 0x29, 0x2c, 0x59, 0x22, 0xb5, 0x9c, 0x19, 0x25, 0x8b, 0xee, 0x8c, 0x7b, 0xa2, 0x6b, 0x78,
	0x57, 0x53, 0x26, 0xb4, 0x1c, 0xc0, 0x2c, 0x65, 0x33, 0xdf, 0xbb, 0xcf, 0x2c, 0xc9, 0x76, 0x39,
	0xd9, 0x36, 0x6e, 0x68, 0x64, 0x81, 0xf4, 0x45, 0x1e, 0x6c, 0x5a, 0x64, 0x4a, 0x03, 0x46, 0xfc,
	0xf8, 0xd3, 0x5a, 0x99, 0xa7, 0xe4, 0x77, 0xbc, 0x32, 0x4f, 0xe9, 0x2f, 0xf1, 0xf7, 0x39, 0xd5,
	0x2e, 0x6e, 0xe9, 0xd5, 0x1b, 0x87, 0x84, 0xbe, 0x24, 0x41, 0x7f, 0xe4, 0xa0, 0x71, 0x4c, 0x84,
	0xbe, 0x72, 0xa1, 0xfc, 0xd2, 0xf3, 0x45, 0xa2, 0x7b, 0xfa, 0xcf, 0x44, 0x5a, 0x81, 0xcd, 0xc7,
	0x49, 0x8f, 0x94, 0xda, 0xe2, 0x27, 0x3c, 0x86, 0x47, 0x68, 0x37, 0x23, 0x06, 0x1a, 0x73, 0x4e,
	0xca, 0xfc, 0x3f, 0x95, 0x4f, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x67, 0x8f, 0xf5, 0xb5, 0xf3,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	CreateSchema(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error)
	ListSchema(ctx context.Context, in *ListSchemaRequest, opts ...grpc.CallOption) (*ListSchemaResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
	UpdateSchema(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error)
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	ListAgent(ctx context.Context, in *ListAgentRequest, opts ...grpc.CallOption) (*ListAgentResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error)
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error)
	LaunchAgent(ctx context.Context, in *LaunchAgentRequest, opts ...grpc.CallOption) (*LaunchAgentResponse, error)
	ShutdownAgent(ctx context.Context, in *ShutdownAgentRequest, opts ...grpc.CallOption) (*ShutdownAgentResponse, error)
	RegisterPublicDID(ctx context.Context, in *PublicDIDRequest, opts ...grpc.CallOption) (*PublicDIDResponse, error)
	GetInvitationForAgent(ctx context.Context, in *AgentInvitiationRequest, opts ...grpc.CallOption) (*AgentInivitationResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) CreateSchema(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error) {
	out := new(CreateSchemaResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/CreateSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListSchema(ctx context.Context, in *ListSchemaRequest, opts ...grpc.CallOption) (*ListSchemaResponse, error) {
	out := new(ListSchemaResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/ListSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/GetSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/DeleteSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateSchema(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error) {
	out := new(UpdateSchemaResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/UpdateSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAgent(ctx context.Context, in *ListAgentRequest, opts ...grpc.CallOption) (*ListAgentResponse, error) {
	out := new(ListAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/ListAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/GetAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error) {
	out := new(DeleteAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error) {
	out := new(UpdateAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/UpdateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) LaunchAgent(ctx context.Context, in *LaunchAgentRequest, opts ...grpc.CallOption) (*LaunchAgentResponse, error) {
	out := new(LaunchAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/LaunchAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ShutdownAgent(ctx context.Context, in *ShutdownAgentRequest, opts ...grpc.CallOption) (*ShutdownAgentResponse, error) {
	out := new(ShutdownAgentResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/ShutdownAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RegisterPublicDID(ctx context.Context, in *PublicDIDRequest, opts ...grpc.CallOption) (*PublicDIDResponse, error) {
	out := new(PublicDIDResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/RegisterPublicDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetInvitationForAgent(ctx context.Context, in *AgentInvitiationRequest, opts ...grpc.CallOption) (*AgentInivitationResponse, error) {
	out := new(AgentInivitationResponse)
	err := c.cc.Invoke(ctx, "/steward.Admin/GetInvitationForAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	CreateSchema(context.Context, *CreateSchemaRequest) (*CreateSchemaResponse, error)
	ListSchema(context.Context, *ListSchemaRequest) (*ListSchemaResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
	UpdateSchema(context.Context, *UpdateSchemaRequest) (*UpdateSchemaResponse, error)
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	ListAgent(context.Context, *ListAgentRequest) (*ListAgentResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error)
	UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error)
	LaunchAgent(context.Context, *LaunchAgentRequest) (*LaunchAgentResponse, error)
	ShutdownAgent(context.Context, *ShutdownAgentRequest) (*ShutdownAgentResponse, error)
	RegisterPublicDID(context.Context, *PublicDIDRequest) (*PublicDIDResponse, error)
	GetInvitationForAgent(context.Context, *AgentInvitiationRequest) (*AgentInivitationResponse, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_CreateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/CreateSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateSchema(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/ListSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListSchema(ctx, req.(*ListSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/DeleteSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteSchema(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/UpdateSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateSchema(ctx, req.(*UpdateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/ListAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAgent(ctx, req.(*ListAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/GetAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/UpdateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_LaunchAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).LaunchAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/LaunchAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).LaunchAgent(ctx, req.(*LaunchAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ShutdownAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ShutdownAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/ShutdownAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ShutdownAgent(ctx, req.(*ShutdownAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RegisterPublicDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RegisterPublicDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/RegisterPublicDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RegisterPublicDID(ctx, req.(*PublicDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetInvitationForAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInvitiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetInvitationForAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steward.Admin/GetInvitationForAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetInvitationForAgent(ctx, req.(*AgentInvitiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "steward.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchema",
			Handler:    _Admin_CreateSchema_Handler,
		},
		{
			MethodName: "ListSchema",
			Handler:    _Admin_ListSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _Admin_GetSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _Admin_DeleteSchema_Handler,
		},
		{
			MethodName: "UpdateSchema",
			Handler:    _Admin_UpdateSchema_Handler,
		},
		{
			MethodName: "CreateAgent",
			Handler:    _Admin_CreateAgent_Handler,
		},
		{
			MethodName: "ListAgent",
			Handler:    _Admin_ListAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _Admin_GetAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _Admin_DeleteAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _Admin_UpdateAgent_Handler,
		},
		{
			MethodName: "LaunchAgent",
			Handler:    _Admin_LaunchAgent_Handler,
		},
		{
			MethodName: "ShutdownAgent",
			Handler:    _Admin_ShutdownAgent_Handler,
		},
		{
			MethodName: "RegisterPublicDID",
			Handler:    _Admin_RegisterPublicDID_Handler,
		},
		{
			MethodName: "GetInvitationForAgent",
			Handler:    _Admin_GetInvitationForAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steward/api/steward_agent.proto",
}
