// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package agent

import (
	"github.com/scoir/canis/pkg/framework"
)

// Injectors from wire.go:

func InitializeAgent(agentID string, conf *framework.Config) (*Agent, error) {
	agent, err := NewAgent(agentID, conf)
	if err != nil {
		return nil, err
	}
	return agent, nil
}
